### ISSUE TITLE
Use Case : Weekday and Month Names

### ISSUE THREAD

**Issue by romulocintra** [tc39/intl-displaynames-v2#1]
Issue to group possible use cases for Weekday and Month Names.

Just for reference : https://github.com/tc39/proposal-intl-displaynames/issues/46

**Comment by romulocintra** [comment]
Things we can actually do with most popular libraries + Temporal

```javascript
// Temporal
Temporal.now.date().day;

// moment
moment().date();

// dayjs
dayjs().date();

// date-fns
import { getDate } from 'date-fns';
getDate(new Date());

// => 14 (Current Day)
```

And to get the WeekDay : 

```javascript

// Temporal
Temporal.now.date().toLocaleString('es-ES', {
  weekday: 'long',
}); // => martes

// moment (only works loading locale strings separately - 4.04 KB)
moment().locale('es-ES').format('dddd'); //=> martes

// dayjs (only works loading locale strings separately - 1.01 KB)
dayjs().locale('es-ES').format('dddd'); //=> martes
```

Just drop some examples to create use cases

**Comment by FrankYFTang** [comment]
I don't get how would you use the above code to get the string for "Monday" in French, for example, or "January" in German, for example.

**Comment by romulocintra** [comment]
> I don't get how would you use the above code to get the string for "Monday" in French, for example, or "January" in German, for example.

The examples above are just code that retrieves the actual day not really for the use case, only to have some idea about the syntax libraries are using.

For months moment has the following syntax: 
```javascript

moment.monthsShort();
["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
moment.months();
["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
```


I'm preparing some use cases based on our own needs, that was the reason why I opened https://github.com/tc39/proposal-intl-displaynames/issues/46 at first

**Comment by FrankYFTang** [comment]
Thanks. I also put down in README.md some way to use the Intl.DateTimeFormat for that to show how error prone it could be. I intentionally use the string to construct the Date because that will create the date in UTC and cause bug but from a glance the users may not be able to notice such difference. Could you read the README.md and propose a PR to merge your write up into READM.md? I love the images you put down here.

**Comment by FrankYFTang** [comment]
Per ECMA402 Jan 2021 meeting discussion, weekday and month name and other date/time related features are removed from v2 spec and let Temporal to handle it instead.
