### ISSUE TITLE
Should calendar eras be included in this proposal?

### ISSUE THREAD

**Issue by justingrant** [tc39/intl-displaynames-v2#17]
Calendar eras (e.g. `B.C.`, `Reiwa`) have names. Should they be supported by this proposal?

If yes, then make sure to handle the case of Japanese eras which don't start on an even year boundary. For example: the current Reiwa era began on `2019-05-01`.   Note that this is a similar case to Adar vs. Adar II-- there's more than one primitive value that's needed to determine the proper name of the thing.

**Comment by FrankYFTang** [comment]
Per ECMA402 Jan 2021 meeting decision, we will keep only "unit" and "calendar" in the v2 spec. All other date/time related will be addressed by Temporal spec
