### ISSUE TITLE
What happened to Date Time Field?

### ISSUE THREAD

**Issue by sffc** [tc39/intl-displaynames-v2#18]
I think the display names for date time fields are still relevant.  For example, you might want a dropdown menu labeled "Month".

**Comment by FrankYFTang** [comment]
In ECMA402 2021-03-11 TG2 meeting we agree to add this feature back to the spec. Frank will revise the spec to include that.

**Comment by sffc** [comment]
2021-03-11 notes: https://github.com/tc39/ecma402/blob/master/meetings/notes-2021-03-11.md#what-happened-to-date-time-field-18
