### ISSUE TITLE
Use Case: Unit name

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/intl-displaynames-v2#2]
During ECMA402 2020-08-13 meeting, @sffc mentioned
"SFC: Peter Edberg wanted unit names for Apple [when I added the function to ICU]. I can look those up."

**Comment by sffc** [comment]
The original ICU ticket is here:

https://unicode-org.atlassian.net/browse/ICU-12029

@macchiati @pedberg-icu @hugovdm @younies Can you share some use cases behind unit display names and whether we should add them to ECMA-402?

**Comment by macchiati** [comment]
I think the unit patterns are very much more important. The display names
would be users in cases like menus or preferences, where you are choosing
which unit to use.

**Comment by FrankYFTang** [comment]
@littledan in 2021-04-20 TC39 meeting questions the need of the type: "unit" and which companies request for such support while I proposed to advance this proposal to Stage 3. Although he later dropped it as a blocker for Stage 3 advancement @sffc list it as one the action item for the proposal champion to work on before we bring it back to TC39 in May again. @pedberg-icu - it would be nice if you can chip in your view if you think adding such support in JavaScript would fulfill the request/need from Apple [or not].

**Comment by FrankYFTang** [comment]
During 2021-05-06 ECMA402 meeting, due to lack of additional companies request other than Google, we decided to remove the support of "unit" for the v2 proposal.
