### ISSUE TITLE
Stage 3 readiness review

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/intl-displaynames-v2#22]
@sffc @ryzokuken @gibson042 

Please raise issue of the current spec text if you see anything missing for Stage 3.

**Comment by codehag** [comment]
Mozilla's bug in case you want to track: https://bugzilla.mozilla.org/show_bug.cgi?id=1693575

**Comment by FrankYFTang** [comment]
ok, since this is already stage 3, I close this issue
