### ISSUE TITLE
Review: Clarify the purpose of [[DialectHandling]] better

### ISSUE THREAD

**Issue by ryzokuken** [tc39/intl-displaynames-v2#24]
Minor review comment, but I feel that https://github.com/tc39/intl-displaynames-v2/blob/f09181795aac6414fa2273658f126163566a0335/displaynames.html#L363 should do a better job of explaining the `[[DialectHandling]]` slot. More specifically, it should mention that the value only affects the result of `type = "language"` and none of the other cases...

**Comment by FrankYFTang** [comment]
> type = "location"

I assume you mean type = "language", right?

**Comment by ryzokuken** [comment]
Oh I am sorry, yes.

**Comment by FrankYFTang** [comment]
Thanks for the feedback. I will looks into this tonight.
