### ISSUE TITLE
Adding "menu" option to dialectHandling

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/intl-displaynames-v2#30]
This is a fork out/ spin off of feature request from https://github.com/tc39/intl-displaynames-v2/issues/29 since the rest of the issue in that issue is about naming and default of already spec out text. 

The issue is about adding a third option of "menu" to the option "dialectHandling".

**Comment by FrankYFTang** [comment]
@anba @sffc @ryzokuken

**Comment by FrankYFTang** [comment]
I dig into ICU and
1. The data in the ICU source/data/lang/*.txt does include the information in lLanguages%menu in parallel to  Languages and Languages%short  
2. But I do not think there are any ICU code use Languages%menu.

**Comment by FrankYFTang** [comment]
In @anba wrote  in https://github.com/tc39/intl-displaynames-v2/issues/29#issue-861374495

```
CLDR defines three choices for language display names:

* dialect
* standard
* menu
The current proposal text doesn't seem to allow the "menu" kind. Should it be supported?
```

I somehow could not find such 3 definition mentioned by @anba in UTS35. Could you provide pointer (URL) to support your claim so I can dig in to research better?

**Comment by FrankYFTang** [comment]
I prefer we leave the support of "menu" out of v2 proposal since there are no clear definition nor prior implementation as I know. For anyone who would like to support that, he/she can open additional PR against ECMA402 later if we can justify the use case, pay load and prior arts.

**Comment by sffc** [comment]
Upstream issues:

- https://unicode-org.atlassian.net/browse/CLDR-13430
- https://unicode-org.atlassian.net/browse/ICU-21549

It seems that @pedberg-icu added the "menu" style to CLDR in 2019, but it is under-specified in UTS 35, and there is no ICU API to access the data.  So I agree with punting this until we get better prior art.

**Comment by ryzokuken** [comment]
Perhaps we could use this thread to voice support on the ICU issue and add the new `languageDisplay` in once it's available?

**Comment by FrankYFTang** [comment]
Per 2021-05-06 ECMA402 (TC39-TG2) meeting, the support of "menu" will be left out for this proposal and revisit once prior arts established by CLDR and ICU.
