### ISSUE TITLE
Rename dialectHandling  to languageDisplay

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/intl-displaynames-v2#31]
In https://github.com/tc39/intl-displaynames-v2/issues/29 @sffc  suggest we rename this dialectHandling to languageDisplay. I spin off that part of request to this issue.

**Comment by ryzokuken** [comment]
+1 for this rename. @anba what do you think?

**Comment by FrankYFTang** [comment]
Here is what @sffc proposed (I prefer to move here as a separated issue) in https://github.com/tc39/intl-displaynames-v2/issues/29#issuecomment-822777071
>If we were to add it to this proposal, the API could be:
```
new Intl.DisplayNames("en", { type: "language", languageDisplay: "standard" })
new Intl.DisplayNames("en", { type: "language", languageDisplay: "dialect" })
```
> This would be parallel to "currencyDisplay" and such in Intl.NumberFormat. The options are relevant only for certain types.

Notice I leave the "menu" issue out, I think that should be discussed and addressed separately in https://github.com/tc39/intl-displaynames-v2/issues/30

**Comment by anba** [comment]
> +1 for this rename. @anba what do you think?

Sounds good to me.

**Comment by sffc** [comment]
Discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2021-05-06.md#rename-dialecthandling-to-languagedisplay-31
