### ISSUE TITLE
Lower case mapping definition missing in 6.1

### ISSUE THREAD

**Issue by anba** [tc39/intl-displaynames-v2#37]
<https://tc39.es/intl-displaynames-v2/#sec-canonicalcodefordisplaynames>:
> ...
> 4. If type is "calendar", then
>  &emsp; a. ...
> &emsp; b. Let code be the result of mapping code to lower case as described in 6.1.

But <https://tc39.es/ecma402/#sec-case-sensitivity-and-case-mapping> doesn't define mapping to lower case. (Only mapping to upper case is currently defined.)

**Comment by FrankYFTang** [comment]
Good catch, this issue pre-exist in the Intl.DisplayNames  (v1) proposal and is already in ECMA402. Let's move that issue under ECMA402 instead.

**Comment by FrankYFTang** [comment]
Close this issue and let https://github.com/tc39/ecma402/issues/576 handle that.
