### ISSUE TITLE
Display names: metazones versus timezones

### ISSUE THREAD

**Issue by sffc** [tc39/intl-displaynames-v2#5]
*Terminology for the purposes of this thread: America/Chicago is a metazone; Central Standard Time is a timezone.*

CLDR provides display names for both timezones and metazones.  For example:

https://github.com/unicode-org/cldr/blob/56a784aa5dc15bed3133297cdf886322eb04cfba/common/main/en.xml#L3359

We should support both.  We should work with Temporal to develop the API.

**Comment by FrankYFTang** [comment]
due to discussion in ECMA402 Jan 2021 meeting, remove timezone support and let Temporal to solve it.
