### ISSUE TITLE
adding abbreviated length

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/intl-displaynames-v2#6]
This is a "move" from issue https://github.com/tc39/proposal-intl-displaynames/issues/74 of the v1 repo

zbraniecki commented on May 20
It seems to me that at the moment DisplayNames doesn't handle abbreviated length of the field.
Is there a reason we decided to skip it or just an omission?

zbraniecki commented on Jun 15
Ah, sure.

So, I understand that for now we removed weekday and month for now (#75), and I assume we intend to bring them back.

If that's the case, then the follow up question is about styles. The proposal currently lists three styles - ["narrow", "short", "long"].
But CLDR handles four styles - ["abbreviated", "narrow", "short", "wide"]. See: https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/en/ca-gregorian.json#L105-L141

I assume that the long in the ECMA402 will map to wide in CLDR, but it doesn't seem like we have an equivalent for abbreviated.

I'd like to know if this is intended to be added later, or for some reason we will not want to support it.

The context is that we have an internal DisplayNames in Firefox for our UI, that we keep a bit more "on the edge" than open API for JS has, because we can deprecate and replace code if needed, but I'd like to keep it in sync with our proposals.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1639515#c10 for context.

@zbraniecki

**Comment by zbraniecki** [comment]
@FrankYFTang can we add it to v2?

**Comment by FrankYFTang** [comment]
but for v2 now we remove the support of weekday and month name from the scope. Then why do we still need it?

**Comment by zbraniecki** [comment]
Ah, damn, good call. I thought this is about language names and region names.

Hmm, I'm wondering what should we do with this in MozIntl :(

**Comment by FrankYFTang** [comment]
close this issue since it is related to removed features
